-- select customer_id, first_name, last_name
-- from customers
-- where customer_id in (
-- 		select o.customer_id from order_items oi
--         join orders o using (order_id)
-- 		where product_id = 3)

-- select distinct customer_id, first_name, last_name
-- from customers c
-- join orders o using(customer_id)
-- join order_items oi using (order_id)
-- where oi.product_id = 3